---
# file: webgoat/task/common.yml

# Load a variable file based on OS
- include_vars: '{{ item }}'
  with_first_found:
    - "vars/{{ ansible_distribution | lower }}.yml"
    - "vars/{{ ansible_os_family | lower }}.yml"
    - "vars/default.yml"